using UnityEngine;

// GENERATED by SuppliedBatch0927Builder (Wasteland ▸ Supplied Batch 0927 ▸ Build All) — do not edit by hand.
// Handle points for the Sept 27 tools and gauntlets, measured from each model's geometry after it was
// turned to match its starter tool's frame.
public static partial class HeldModelPlacement
{
    static Profile Generated(string modelName)
    {
        Vector3 x = Vector3.right, y = Vector3.up, z = Vector3.forward;
        return modelName switch
        {
            "SteelPickaxe" => new Profile(new Vector3(0.057f,-0.2f,0.055f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),0.85f),
            "AlloyPickaxe" => new Profile(new Vector3(0.057f,-0.2f,0.055f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),0.85f),
            "TitaniumPickaxe" => new Profile(new Vector3(0.004f,-0.221f,-0.033f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),0.85f),
            "SteelHatchet" => new Profile(new Vector3(-0.268f,-0.248f,0.002f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),0.65f),
            "AlloyHatchet" => new Profile(new Vector3(-0.315f,-0.25f,-0.084f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),0.65f),
            "TitaniumHatchet" => new Profile(new Vector3(-0.247f,-0.252f,-0.005f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),0.65f),
            "SteelFishingRod" => new Profile(new Vector3(0.253f,-0.34f,0.087f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),1.8f),
            "AlloyFishingRod" => new Profile(new Vector3(0.272f,-0.35f,-0.231f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),1.8f),
            "TitaniumFishingRod" => new Profile(new Vector3(0.341f,-0.345f,-0.007f),new Vector3(0f,1f,0f),new Vector3(0f,0f,1f),1.8f),
            "NeonGauntletRight" => new Profile(new Vector3(0f,0f,-.08f),z,y,0.3f),
            "NeonGauntletLeft" => new Profile(new Vector3(0f,0f,-.08f),z,y,0.3f),
            "SurgeGauntletRight" => new Profile(new Vector3(0f,0f,-.08f),z,y,0.38f),
            "SurgeGauntletLeft" => new Profile(new Vector3(0f,0f,-.08f),z,y,0.38f),
            "InfernoGauntletRight" => new Profile(new Vector3(0f,0f,-.08f),z,y,0.34f),
            "InfernoGauntletLeft" => new Profile(new Vector3(0f,0f,-.08f),z,y,0.34f),
            _ => default
        };
    }
}
